/**
 * @(#)SeguriSignServiceImpl.java 14/03/2017
 *
 * Copyright (C) 2017 Instituto Nacional Electoral (INE).
 * 
 * Todos los derechos reservados.
 */
package mx.ine.gestion.seguridad;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.org.ine.servicios.utils.ApplicationContextUtils;

import org.jboss.logging.Logger;

import seguridata.segurisign.service.SeguriSignService;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 * Clase proporcionada para firmar, comentarios y descripciones tal cual se entrego.
 */
@WebServiceClient(name = "SeguriSignService", targetNamespace = "http://service.segurisign.seguridata/")
public class SeguriSignServiceImpl extends Service {

	private static final Logger log = Logger.getLogger(SeguriSignServiceImpl.class);
    private final static URL SEGURISIGNSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEGURISIGNSERVICE_EXCEPTION;
    private final static QName SEGURISIGNSERVICE_QNAME = new QName("http://service.segurisign.seguridata/", "SeguriSignService");
    private static String ruta = (String) ApplicationContextUtils.getApplicationContext().getBean("seguriSign");
    
    static {

        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(ruta);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (Throwable t){
        	log.error("SeguriSignServiceImpl:: ",t);
        }
        SEGURISIGNSERVICE_WSDL_LOCATION = url;
        SEGURISIGNSERVICE_EXCEPTION = e;
    }

    public SeguriSignServiceImpl() {
        super(__getWsdlLocation(), SEGURISIGNSERVICE_QNAME);
    }

    public SeguriSignServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SEGURISIGNSERVICE_QNAME);
    }

    public SeguriSignServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SeguriSignService
     */
    @WebEndpoint(name = "SeguriSignServicePort")
    public SeguriSignService getSeguriSignServicePort() {
        return super.getPort(new QName("http://service.segurisign.seguridata/", "SeguriSignServicePort"), SeguriSignService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeguriSignService
     */
    @WebEndpoint(name = "SeguriSignServicePort")
    public SeguriSignService getSeguriSignServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.segurisign.seguridata/", "SeguriSignServicePort"), SeguriSignService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEGURISIGNSERVICE_EXCEPTION!= null) {
            throw SEGURISIGNSERVICE_EXCEPTION;
        }
        return SEGURISIGNSERVICE_WSDL_LOCATION;
    }

	/**
	 * @return the ruta
	 */
	public static String getRuta() {
		return ruta;
	}

	/**
	 * @param ruta the ruta to set
	 */
	public static void setRuta(String ruta) {
		SeguriSignServiceImpl.ruta = ruta;
	}
}