/**
 * 
 *  Funcion que valida palabras de un campo de texto
 * 
 */

       //función para regresar la pantalla al inicio en caso de que existan errores al someter el formulario.
  	  			function verificarPalabras(cadena) {	
 	  			   
  	  				if (cadena==""){
  	  					return "";
  	  				}
  	  					// Elimina los saltos de línea del texto
  	  					var strSinSaltos = cadena.split("\n").join(" ");
	  	  				var str = strSinSaltos;
		  	  		    var texto = str.split(" ");
		  	  		    var strLimpia = "";
		  	  		    var esReservada = 0;

		  	  		    //palabras reservadas
		  	  		    var diccionarioSQL    = "ABSOLUTE EXEC OVERLAPS ACTION EXECUTE PAD ADA EXISTS PARTIAL ADD EXTERNAL PASCAL ALL EXTRACT POSITION ALLOCATE FALSE ALTER FETCH PREPARE AND FIRST PRESERVE ANY FLOAT PRIMARY ARE FOR PRIOR AS FOREIGN PRIVILEGES ASC FORTRAN PROCEDURE ASSERTION FOUND PUBLIC AT FROM READ AUTHORIZATION FULL AVG GET REFERENCES BEGIN GLOBAL RELATIVE BETWEEN GO RESTRICT BIT GOTO REVOKE BIT_LENGTH GRANT RIGHT BOTH GROUP ROLLBACK BY HAVING ROWS CASCADE HOUR SCHEMA CASCADED IDENTITY SCROLL CASE IMMEDIATE SECOND CAST IN SECTION CATALOG INCLUDE SELECT CHAR INDEX SESSION CHAR_LENGTH INDICATOR SESSION_USER CHARACTER INITIALLY SET CHARACTER_LENGTH INNER SIZE CHECK INPUT SMALLINT CLOSE INSENSITIVE SOME COALESCE INSERT SPACE COLLATE INT SQL COLLATION INTEGER SQLCA COLUMN INTERSECT SQLCODE COMMIT INTERVAL SQLERROR CONNECT INTO SQLSTATE CONNECTION IS SQLWARNING CONSTRAINT ISOLATION SUBSTRING CONSTRAINTS JOIN SUM KEY SYSTEM_USER CONVERT LANGUAGE TABLE CORRESPONDING LAST TEMPORARY COUNT LEADING THEN CREATE LEFT TIME CROSS LEVEL TIMESTAMP CURRENT LIKE TIMEZONE_HOUR CURRENT_DATE TIMEZONE_MINUTE CURRENT_TIME LOWER TO CURRENT_TIMESTAMP MATCH TRAILING CURRENT_USER MAX TRANSACTION MIN TRANSLATE DATE MINUTE TRANSLATION DAY MODULE TRIM DEALLOCATE MONTH TRUE DEC NAMES NATIONAL UNIQUE DECLARE UNKNOWN DEFAULT NCHAR UPDATE DEFERRABLE NEXT UPPER DEFERRED USAGE DELETE NONE USER DESC NOT USING NULL VALUE NULLIF VALUES DIAGNOSTICS NUMERIC VARCHAR DISCONNECT OCTET_LENGTH VARYING DISTINCT OF VIEW DOMAIN ON WHEN DOUBLE ONLY WHENEVER DROP OPEN WHERE ELSE OPTION WITH END OR WORK END-EXEC ORDER WRITE ESCAPE OUTER YEAR EXCEPT OUTPUT ZONE EXCEPTION ";
		  	  		    var diccionarioHTML   = "ADDRESS APPLET BASEFONT BIG BLOCKQUOTE BODY BR CAPTION CENTER CITE CODE DD DFN DIR DIV DL DT EM FONT FORM H1 H2 H3 H4 H5 H6 HEAD HR HTML IMG INPUT ISINDEX KBD LINK LI MAP OL OPTION PARAM PRE SAMP SCRIPT SELECT SMALL STRIKE STRONG STYLE SUB SUP TABLE TD TEXTAREA TH TITLE TR TT UL VAR ";
		  	  		    var diccionarioJava   = "ABSTRACT ASSERT BOOLEAN BREAK BYTE CASE CATCH CHAR CLASS CONST DEFAULT DO DOUBLE ELSE ENUM EXTENDS FINALLY FLOAT FOR GOTO IF IMPLEMENTS IMPORT INSTANCEOF INT INTERFACE LONG NATIVE NEW PACKAGE PRIVATE PROTECTED PUBLIC RETURN SHORT STATIC STRICTFP SUPER SWITCH SYNCHRONIZED THIS THROW THROWS TRANSIENT TRY VOID VOLATILE WHILE ";
		  	  		    var diccionarioPrimeF = "COMPONENT IFALLGRANTED IFANYGRANTED IFGRANTED IFNONEGRANTED REMOTEUSER USERPRINCIPAL WIDGETVAR WIDGETVARFROMCONTEXT ACCORDIONPANEL AJAX AJAXSTATUS AUTOCOMPLETE BARCHART BLOCKUI BREADCRUMB BUBBLECHART BUTTON CALENDAR CAPTCHA CAROUSEL CELLEDITOR CLIENTVALIDATOR CLOCK COLLECTOR COLORPICKER COLUMN COLUMNGROUP COLUMNS COMMANDBUTTON COMMANDLINK CONFIRM CONFIRMDIALOG CONTEXTMENU DASHBOARD DATAEXPORTER DATAGRID DATALIST DATATABLE DEFAULTCOMMAND DIALOG DOCK DONUTCHART DRAGGABLE DROPPABLE EDITOR EFFECT FEEDREADER FIELDSET FILEDOWNLOAD FILEUPLOAD FOCUS FRAGMENT GALLERIA GMAP GMAPINFOWINDOW GRAPHICIMAGE GROWL HOTKEY IDLEMONITOR IMAGECOMPARE IMAGECROPPER IMAGESWITCH INPLACE INPUTMASK INPUTTEXT INPUTTEXTAREA KEYBOARD LAYOUT LAYOUTUNIT LIGHTBOX LINECHART LOG MEDIA MEGAMENU MENUBAR MENUBUTTON MENUITEM MESSAGE MESSAGES METERGAUGECHART MINDMAP MULTISELECTLISTBOX NOTIFICATIONBAR OHLCCHART ORDERLIST OUTPUTLABEL OUTPUTPANEL OVERLAYPANEL PANELGRID PANELMENU PASSWORD PHOTOCAM PICKLIST PIECHART POLL PRINTER PROGRESSBAR RADIOBUTTON RATING REMOTECOMMAND RESETINPUT RESIZABLE RING ROW ROWEDITOR ROWEXPANSION ROWTOGGLER SCHEDULE SCROLLPANEL SELECTBOOLEANBUTTON SELECTBOOLEANCHECKBOX SELECTCHECKBOXMENU SELECTMANYBUTTON SELECTMANYCHECKBOX SELECTMANYMENU SELECTONEBUTTON SELECTONELISTBOX SELECTONEMENU SELECTONERADIO SEPARATOR SLIDEMENU SLIDER SOCKET SPACER SPINNER SPLITBUTTON STACK STICKY SUBMENU SUBTABLE SUMMARYROW TAB TABMENU TABVIEW TAGCLOUD THEMESWITCHER TIEREDMENU TOOLBAR TOOLBARGROUP TOOLTIP TREE TREENODE TREETABLE WATERMARK WIZARD ";
		  	  		    var diccionarioPhp    = "BREACK AND ARRAY AS SWITCH CATCH CLASS CLONE CONST DIE DO ELSE ELSEIF EMPTY EDDECLARE ENDIF ENDWHILE ENDFOR ENDFOREACH ENDSWITCH EVAL FINALLY FOR FOREACH FUNCTION GLOBAL GOTO IF IMPLEMENTS INCLUDE INCLUDE_ONCE INSTANCEOF INTERFACE ISSET LIST NAMESPACE OR PRINT PRIVATE PUBLIC PROTECTED REQUIRE REQUIRE_ONCE RETURN STATIC THROW TRY UNSET VAR WHILE XOR ";
		  	  		    var diccionarioUnix   = "PWD MKDIR CD LS CHMOD MV CP RM RMDIR LPR WC FILE FIND TAR GZIP MORE LESS CAT MORE LESS CAT DIFF VI VIEW MAN WHOAMI WHO FINGER DATE CLEAR HISTORY FTP RLOGIN SSH TELNET PS KILL JOBS EXIT ";
		  	  		    var diccionarioDOS    = "ASSOC AT ATTRIB BREAK CALCS CALL CD CHCP CHDIR CHKDSK CHKNTFS CLS CMD COMP COMPACT CONVERT COPY DATE DISKPART DISKCOMP DOSKEY DRIVERQUERY ENDLOCAL ERASE EXIT FC FIND FINDSTR FOR FORMAT FSUTIL FTYPE GOTO GPRESULT GRAFTABL HELP ICACLS IF LABEL MD MKDIR MKLINK MODE MORE MOVE OPENFILES PATH PAUSE POPD PRINT PROMPT PUSHD RD RECOVER REM REN RENAME REPLACE RMDIR ROBOCOPY SC SCHTASKS SET SETLOCAL SHIFT SHUTDOWN SORT START SUBST SYSTEMINFO TASKKILL TASKLIST TIME TITLE TREE TYPE VERIFY WMIC XCOPY ";
	
		  	  		    //union de diccionarios
		  	  		    var diccionarios = diccionarioSQL + diccionarioHTML + diccionarioJava + diccionarioPrimeF + diccionarioPhp + diccionarioUnix +  diccionarioDOS;
		  	  		    var reservadas = diccionarios.split(" ");
		  	  		    
		  	  		    //reconstruir texto sin palabras reservadas
		  	  		    for (var i=0; i < texto.length; i++) {
		  	  		        //alert(texto[i] + " / " + texto.length);
		  	  		    	esReservada = 0;
		  	  		    	var strtemp = texto[i].toUpperCase();
		  	  		    	for(var j=0; j < reservadas.length; j++){
		  	  		    	
		  	  		    		if (strtemp == reservadas[j] && strtemp != ""){
		  	  		    			strLimpia = strLimpia + " ";
		  	  		    			esReservada = 1;
		  	  		    		}
	
		  	  		    	}
	  	  		    		if (esReservada != 1){
			  	  		    	strLimpia = strLimpia + " " + texto[i];
			  	  		    }
		  	  		    }

		  	  		    return strLimpia.trim();
				}
